site_name: desi_lss_datamodel
site_url: https://aureliocarnero.github.io/desi_lss_datamodel.github.io/
nav:
    - Home: index.html
    - Version 2.x:
        - Getting Started: v2/getting-started.md
        - Types:
            - Comments: v2/types/comments.md
    - Version 1.x:
        - Types:
            - Comments: v1/types/comments.md
            - Posts: v1/types/posts.md


theme: readthedocs
